# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import datetime
import os
import re
import sys

sys.path.insert(0, os.path.abspath(".."))

repo_version = "unknown"
# Determine short version by file in repo
if os.path.isfile("../VERSION"):
    with open("../VERSION") as f:
        repo_version = f.readline().strip()


# -- Project information -----------------------------------------------------

project = "Omnistat"
# End year tracks the build date so the footer copyright stays current.
copyright = f"2023-{datetime.date.today().year}, Advanced Micro Devices, Inc."
author = "AMD Research"

# The short X.Y version
version = repo_version
# The full version, including alpha/beta/rc tags
release = repo_version

# Sidebar / left-nav title: "Omnistat <version>" with the version sourced
# from the repo VERSION file (avoids Sphinx's default "... documentation").
html_title = f"{project} {version}"

# Minimum supported ROCm version, substituted into docs as {__ROCM_MIN_VERSION__}.
rocm_min_version = "6.3.0"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.githubpages",
    "rocm_docs",
    "sphinxmark",
]

show_authors = True


# rocm-docs-core already enables replacements, dollarmath, colon_fence,
# substitution, etc.; only override the heading-anchor depth here.
myst_heading_anchors = 4

numfig = True
numfig_format = {"figure": "Figure %s"}


sphinxmark_enable = False
sphinxmark_image = "text"
sphinxmark_text = "D R A F T"
sphinxmark_text_size = 80
sphinxmark_div = "document"
sphinxmark_fixed = False
sphinxmark_text_rotation = 30
sphinxmark_text_color = (128, 128, 128)
sphinxmark_text_spacing = 800
sphinxmark_text_opacity = 30

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "requirements-docs.txt",
    # Local build virtualenvs living inside docs/ (don't scan site-packages).
    "venv",
    "venv/**",
    ".venv",
    ".venv/**",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# options for latex output
latex_engine = "lualatex"
latex_show_urls = "footnote"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "rocm_docs_theme"

# External table of contents (sphinx-external-toc, provided by rocm-docs-core).
external_toc_path = "./sphinx/_toc.yml"

# Don't pull intersphinx mappings for other ROCm projects
external_projects = []

# Build offline: don't hit the GitHub API on every cold/config-changed build to
# fetch the project mapping from ROCm/rocm-docs-core@develop.  Anonymous API
# calls are capped at 60/hour per IP, and rocm-docs-core responds to the 403 by
# sleeping in a long backoff, which looks like a hung build.  Leaving this unset
# makes it fall back to the projects.yaml bundled with the installed rocm_docs
# package -- and with external_projects empty above, those mappings are unused
# anyway.  Set this back to "ROCm/rocm-docs-core" to restore remote fetching.
external_projects_remote_repository = ""

# Local template overrides (e.g. footer copyright); searched before the theme's.
templates_path = ["_templates"]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["static"]

latex_elements = {
    "sphinxsetup": "verbatimwrapslines=true, verbatimforcewraps=true",
}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
# htmlhelp_basename = ""

html_theme_options = {
    "flavor": "generic",
    "header_title": "Omnistat",
    "header_link": "https://rocm.github.io/omnistat/",
    "link_main_doc": False,
    "analytics": {"google_analytics_id": "G-8K5QQMVD1V"},
    # Pin the top-bar links explicitly (flavor defaults vary by version).
    "nav_secondary_items": {
        "GitHub": "https://github.com/ROCm/omnistat",
        "Support": "https://github.com/ROCm/omnistat/issues/new/choose",
    },
    # Expand nav sub-items by default instead of hiding them behind a click.
    "show_navbar_depth": 2,
}

html_css_files = ["custom.css"]


# ---------------------------------------------------------------------------
# Public wheel availability toggle.
#
# Sources mark the conditional content with HTML comments:
#
#   <!-- if-release:start -->      shown only when release_wheels_public = True
#   <!-- if-release:end -->
#
#   <!-- if-norelease:start -->    shown only when release_wheels_public = False
#   <!-- if-norelease:end -->
#
# The marker lines themselves are always stripped before parsing, so they never
# reach sphinx-design.  This has to happen on the raw source rather than with
# the `only` or `ifconfig` directives, because sphinx-design validates the
# children of a `tab-set` at parse time and errors out on any other node type.
# ---------------------------------------------------------------------------
release_wheels_public = False

_CONDITIONAL_BLOCK = re.compile(
    r"^[ \t]*<!--[ \t]*if-(no)?release:start[ \t]*-->[ \t]*\n"
    r"(.*?)"
    r"^[ \t]*<!--[ \t]*if-(?:no)?release:end[ \t]*-->[ \t]*\n",
    re.DOTALL | re.MULTILINE,
)


# function to show/hide released-wheel content based on release_wheels_public
def toggleReleaseContent(app, docname, source):
    public = app.config.release_wheels_public

    def keepOrDrop(match):
        negated = match.group(1) is not None
        return match.group(2) if (public != negated) else ""

    source[0] = _CONDITIONAL_BLOCK.sub(keepOrDrop, source[0])


# app setup hook
def setup(app):
    app.add_config_value("docstring_replacements", {}, True)
    app.add_config_value("release_wheels_public", False, "env")
    app.connect("source-read", replaceString)
    app.connect("source-read", toggleReleaseContent)


# function to replace version string througout documentation


def replaceString(app, docname, source):
    result = source[0]
    for key in app.config.docstring_replacements:
        result = result.replace(key, app.config.docstring_replacements[key])
    source[0] = result


docstring_replacements = {
    "{__VERSION__}": version,
    "{__ROCM_MIN_VERSION__}": rocm_min_version,
}
